(xui.Locale.en||(xui.Locale.en={})).RAD={
    message:"System message!",
    noMessage:"Create Responsive HTML5 Apps Without Coding!",
    soon:'Coming soon',
    ok:'OK',
    cancel:'Cancel',
    'close':'Close',
    save:'Save',
    notsave:'Not save',
    notsave2:'You are about to close a window without saving it.<p>Click [Yes] to discard and continue or [No] to go back for saving action.',
    notsave3:'You have NOT saved your modifications.<p>Click [Yes] to continue anyway or [No] to go back for saving.',
    checkOK:'Congratulations! No syntax error yet!',
    en:'English',
    cn:'Chinese',
    ja:"Japanese", 
    tw:'Traditional Chinese',
    ru:'Russian',
    langTips:'Switch Locale',
    selFile: "Choose File",
    selFilePath: "Please select a file path",

    spabuilder:{
        nosavefirst:'You have unsaved changes. Are you sure you want to discard current changes?',
        menubar:{
            servicetester:'EUSUI Service Tester',
            backendcode:'Back-end Service Code',
            php:'PHP Code',
            csharp:'C# Code',
            java:'JAVA Code',
            links:'Links',
            xui:'itjds.net',
            gcodelist:'Google Code Download List',
            cookbook:'CookBook',
            api:'API Documentation',
            codesnipt:'Code Snippet',
            forum: 'Go to Forum...',
            jsoneditor:'JSON Editor',
            commecial:'Commercial Support',
            video:'Introduction Video',
            about:'About'
        },
        st_title:"EUSUI Service Test",
        st_nodata:"Need to check your uri!",
        st_uri:"Service URI",
        st_queryobj:"Request Query Object",
        st_createcode:"Create Request Code",
        st_send:"Send Request To Service",
        st_sending:"Trying...",
        st_result:"Result",
        st_format:"Format",
        st_method:"Query Method"
    },
    
    builder:{
        open:'Open',
        openTips:'Save or download file.',
        save:'Deploy',
        saveTips:'Deploy Application.',
        run:'Debug',
        runTips:'Debug Application.',
        dftThemeTips:'To switch theme',
        advancedBuilder:'Advanced',
        originalFile:"Original file: ",
        issave2server:"Do you mean to overwrite the original server file?",
        save2serverOK:'Saved to server successfully',
        nosavefirst:'You have unsaved changes. Are you sure you want to discard current changes?',
        
        savetoserver:'Save to original file (in server)',
        saveasjs: "EUSUI class file(.js) ",
        saveashtml: "Html file",
        saveasweb: "Web deploy package",
        saveaswin: "Windows 32 platform deploy",
        saveaswin64: "Windows 64 platform deploy",
        saveaslinux: "Linux 32 platform deploy",
        saveaslinux64: "Linux 64 platform deploy",
        saveasosx64: "OS X 64 platform deploy",
        saveasmobile:"Mobile platforms Deploy",
        
        noexist:"$0 doesn't exist!"
    },
    
    menu:{
        file:'Project',
        newproject:'New Project',
        openproject:'Open Project',
        closeproject:'Close Project',
        newfile:'New File',
        openfile:'Open File',
        closefile:'Close File',
        deleteproject:'Delete Project',
        save:'Save',
        saveall:'Save All',

        tools: 'Tools',
            servicetester:"EUSUI Service Test",
            command:'Command Window',
            jsoneditor:'JSON Editor',
            
            cookbook:'CookBook',
            api:'API Documentation',
            codesnipt:'Code Snippet',
            backendcode:'Back-end Service Code',
                php:'PHP Code',
                csharp:'C# Code',
                java:'JAVA Code',
            spy:'Components Spy',

        build: 'Build',
        debug:'Debug Application',
        release: 'Deploy',
        setting: 'Build Setting',

        help: 'Help',
        simple: 'Simple Version',
        video:'Introduction Video',
        movews:'Move Workspace',
        editxml:'PhoeGap Build Configuring',
        editcfg:'NW Package Configuring',
        editorTheme:"Editor Theme Configure",
        forum: 'Go to Forum...',
        license:'License',
        gpllicense:'LGPL License',
        clicense: 'Commercial License',
        purchase:'Purchase License',
        about: 'About...'
    },
    tool:{
        newp:'Create a New Project',
        open:'Open an Existing Project',
        save:'Save Files',
        saveall:'Save All Changed Files',
        command:'Open Command Window',
        spy:'Open Widget Spy Window',
        ec:'Translate Language',
        manual:'Visual Builder Manual...',
        api:'Components API Reference...',              
        demo:'Samples',
        flash:'Flash Video Show'
    },
    tool2:{
        'new':'Add files',
        del: 'Delete Files',
        new2: 'Add file or directory',
        copy2:'Copy file',
        modify:'Modify name',
        del2: 'Delete file or directory',
        refresh:'Refresh Project Files',
        more:'File/Folder Functions',
        explore:'Show in a file manager',
        editastext:"Open in text editor",
        refreshOK:'Project Refreshed!'
    },

    pm:{
        title:'Project',
        html:'HTML files',
        js:'Class files'
    },
    ps:{
        noselected:'Please Select a Project First',
        noprj:'No Project Open',
        getting:'Getting Project List...',
        saved:'$0 File(s) Saved',
        noSaved:'No Files Modified Since Last Saving'
    },
    projectPro:{
        type:"Template type:",
        template:"Template list:",
        name:"Project Name :",
        'class':"Class Name :",
        pagefile:"Main File :",
        classfile:"Class File :",
        onlyword:'Words(3-15) Allowed Only',
        invalid :'Some Fileds Invalid!'
    },
    dialog:{
        newone:'Create a New Project...',
        select:'Select a Project to Open'
    },
    JSEditor:{
        'to':'Switch to ',
        sv:'Code View',
        dv:'Design View',
        svtips:'Code Editor',
        dvtips:'Visual IDE for Design UI Widgets',
        codeerr:'There are syntax errors in the code!',
        specifytype:"Specify type",
        clickapi:"API window"
    },
    pageEditor:{
        check:"Syntax Check",
        'reset':"Reset Code",
        checktips:"Check Code",
        resettips:"Reset Code to Original Form",
        formatted:'Formatted Code',
        outline:'Class Outline',
        'search':'Search',
        'replace':'Replace',
        searchreplace:'Find and Replace',
        replacesearch:'Replace / Find',
        replacewith:'Replace',
        replaceall:'Replace All',
        findnone:'No Result',
        replaceCount:'$0 matched replaced',
        jumpto:'Jump to line',
        indentall:"Re-indent",
        outlinetips:'Class Outline',
        'searchtips':'Search',
        'replacetips':'Replace',
        jumptotips:'Jump to line',
        indentalltips:"Re-indent",
        modeDlgCap:"Select a rendering mode please"
    },
    classtool:{
        err1:'Invalid Code Format, Please Go Back to Have a Check!',
        err2:'Invalid Code Format, Please Go Back to Have a Check!',
        err3:'Invalid Code Format, Please Go Back to Have a Check!',
        err4:'Invalid Code Format, Please Go Back to Have a Check!',
        noClass:'Not a single EUSUI Class File!'
    },
    designer:{
        toolsbox:'Tools Box',
        configwnd:'Component config',
        eventbfrtag:'',
        eventontag:'',
        eventafttag:'',
        
        emptyContent:'Empty Content First...',
        prepare:'Prepare Classes...',
        createContent:'Refresh design content...',
        loading:'Loading ',
        comCodeErr:'An Error Occurs in Function "iniComponents", Please Go Back to Check the Code',
        nameExists:'A Widget Named "$0" Exists Already!',
        domIdExists:'A DOM node wich id "$0" exists already!',
        domIdValid:'DOM id only allows char or number',
        confirmdel:'Delete?',
        confirmdel2:"Are You Sure to Delete the Selected  Component(s) or Module(s)?",
        confirmrefresh1: "Refresh Design View from Code",
        confirmrefresh2: "UI has been changed, 'refresh' will result in loss of these changes, whether to refresh?",
        refreshOK:'Refreshed!',
        wlist: 'Widgets List',
        weditor:'Widget Editor',
        gridcol1: 'property',
        gridcol2: 'value',
        gridcol3: 'binder',
        clipboard:'Clipboard',
        pasted: '$0 widgets pasted into the current container!',
        clearClipboard:'Clipboard has been emptied!',
        copyOK:'$0 widgets copied to clipboard',
        cutOK:'$0 widgets cutted to clipboard',
        colneOK:'$0 widgets cloned into current container',
        openwidgets:'Expand/Fold the widgets list',
        dragwidget1:'You can drag this widget to the design canvas or any container',
        dragwidget2:'You can only drag this widget to the SVG Paper',
        openapi:'DblClick to open API window',
        tool:{
            viewsize:"View Size",
            refresh:"Refresh the Design View",
            tocode:"Serialize controls to JS code",
            tojson:"Serialize controls to JSON code",
            left: 'Align to left',
            center:'Align to center',
            right:'Align to right',
            top:'Align to top',
            middle:'Align to middle',
            bottom:'Align to bottom',
            width:'Same width',
            wh:'Same width and height',
            height:'Same height',
            toplayer: 'To top layer',
            bottomlayer: 'To bottom layer',
            gridxy: 'Set position to grid',
            gridwh: 'Set size to grid',
            "copy":'Copy selected controls [Ctrl+C]',
            "cut":'Cut selected controls [Ctrl+X]',
            "paste":'Paste copied to the current container [Ctrl+V]',
            clone:'Clone selected controls [Ctrl+Alt+X]',
            'delete': 'Delete [Delete]',
            aligngroup : 'Align',
            posgroup : 'Grid&Layer',

            pathedit:"Edit path",
            hmirror : 'Flip horizontally',
            vmirror : 'Flip vertically',
            r90 : 'Rotate 90 clockwise',
            r270 : 'Rotate 90 counter-clockwise',
            freeze : 'Reset transforms',
            
            addpath : "Add path node",
            delpath : "Remove path node",
            openpath : "Open path",
            closepath : "Close path",
            undo : "Undo",
            redo : "Redo",
            mobile : "Show mobile device frame"
        },
        msg:{
            "annoncement1":"<strong>EUSUI is totally free for Non-Profit Individual Use</strong>. ",
            "annoncement2":" You must <a href=http://www.itjds.net/order.html target=_blank style='font-weight:bold'>purchase</a> a License for commercial/client work, and we offer <a href=http://www.itjds.net/order.html target=_blank style='font-weight:bold'>reduced prices</a> for Non-Profit organization use.",
            "renamefileok":"Renamed successfully! If it affected any XUI class file, maybe you should modify the corresponding XUI class name."
        }
    },
    addfile:{
        caption:'Add file to Project...',
        sel:'Select the target Folder',
        filename:'Name',
        filenameformat:'characters only',
        add:'Add',
        "empty":"Empty File",
        'iImg':'Upload a Picture',
        'iDir':'Folder',
        'iHtml':'HTML',
        'iCSS':'CSS',
        'iJs':'JS',
        'iXuiTpl':'XUI Page',
        'iModule':'XUI Module',
        'iNewPage':'[Blank Page]',
        'iNewModule':'[Blank Module]',
        'iJson':'JSON',
        'iPhp':'PHP',
        'iUpload':'Upload a file',
        'target':'Target',
        filetype:'Type',
        notarget:'File or Directory to be built does NOT exist',
        invalidExts: 'The file type is not allowed',
        invalidName: 'Specify file name please, only numbers and letters allowed'
    },
    delfile:{
        caption:'Delete Files From Project...',
        sel:'Select target files or folders',
        notarget:'Target files or folders does NOT exist',
        confirmdel:'Delete?',
        confirmdel2:"Are You Sure to Delete the $0 Selected  Files or Folders?",
        confirmdel3:"Are You Sure to Delete the current project?"
    },
    editorTheme:{
        name:"Editor Theme Configure",
        selTheme:"Select a theme for editor",
        selFontSize:"Specify font size",
        lineWrapping:"Line Wrapping"
    },
    phonegap:{
                recommand: '<div style="padding$:4px"><font color="FF0000"><b>Strongly recommended to use your own account.</b><br>You can <font color="FF0000">create account at http$://build.phonegap.com.</font></div>'
    }
};
